name: testing
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  import_sorter: ^4.6.0

#flutter pub run import_sorter:main -e
#pub run import_sorter:main -e if normal dart application
import_sorter:
  emojis: false # Optional, defaults to false
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/tests\/*


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
