name: hotels
description: hotels

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #flutter_svg: ^2.0.5
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  #carousel_slider:
  # git:
  #    url: https://github.com/serenader2014/flutter_carousel_slider
  #    ref: null-safty
  #    path:
  #This is a simple Service Locator for Dart and Flutter projects
  get_it: ^7.6.0
  import_sorter: ^4.6.0
  #provider: ^6.0.4
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
  #dart pub run build_runner watch
  #The build_runner package exposes a binary by the same name, which can be invoked using dart run build_runner <command>.
  #The available commands are build, watch, serve, and test.
  #build: Runs a single build and exits.
  #watch: Runs a persistent build server that watches the files system for edits and does rebuilds as necessary.
  #serve: Same as watch, but runs a development server as well.
  #  By default this serves the web and test directories, on port 8080 and 8081 respectively. See below for how to configure this.
  #test: Runs a single build, creates a merged output directory, and then runs dart run test --precompiled <merged-output-dir>. See below for instructions on passing custom args to the test command.
  #


  http: ^1.0.0
  json_annotation:

#flutter pub run import_sorter:main -e
#pub run import_sorter:main -e if normal dart application
import_sorter:
  emojis: false # Optional, defaults to false
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/tests\/*

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
